UPDATE PHONGKHAMBENH SET KYHIEU='xn' WHERE IDPHONGKHAMBENH=14
UPDATE PHONGKHAMBENH SET KYHIEU='SIEUAM' WHERE IDPHONGKHAMBENH=27
UPDATE PHONGKHAMBENH SET KYHIEU='XQ' WHERE IDPHONGKHAMBENH=28
UPDATE PHONGKHAMBENH SET KYHIEU='ECG' WHERE IDPHONGKHAMBENH=21
UPDATE PHONGKHAMBENH SET KYHIEU='KHAC' WHERE KYHIEU IS NULL