UPDATE PHONGKHAMBENH SET KYHIEU='xn' WHERE IDPHONGKHAMBENH=3
UPDATE PHONGKHAMBENH SET KYHIEU='SIEUAM' WHERE IDPHONGKHAMBENH=0
UPDATE PHONGKHAMBENH SET KYHIEU='XQ' WHERE IDPHONGKHAMBENH=0
UPDATE PHONGKHAMBENH SET KYHIEU='ECG' WHERE IDPHONGKHAMBENH=6
UPDATE PHONGKHAMBENH SET KYHIEU='KHAC' WHERE KYHIEU IS NULL